name: Understanding cache github actions

on:
  workflow_dispatch:

jobs:
  testing_cache:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v4.2.2

      - name: cache action
        uses: actions/cache@v4.2.3
        with:
          path: ~/.npm
          key: npm-${{ runner.os }}-${{ hashFiles("package-lock.json") }}
          restore-keys: |
            npm-${{ runner.os }}-

      - name: Installing dependecies
        run: npm ci 
