name: Building docker images using ghcr

on:
  push:
    tags:
      - "v*"

jobs:
  build_images:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v4.2.2

      - name: Setup the docker buildx
        uses: docker/setup-buildx-action@v3.11.1
        with:
          version: latest

      - name: Log in to GHCR
        uses: docker/login-action@v3.4.0
        with:
          username: "${{ secrets.GHCR_USERNAME }}"
          password: "${{ secrets.GHCR_TOKEN }}"

      - name: Build and push the image
        uses: docker/build-push-action@v6.18.0
        with:
          context: .
          file: Dockerfile
          tags: ghcr.io/${{ github.repository_owner }}/my-app:${{ github.ref_name }}

      - name: Logout from GHCR
        run: docker logout ghcr.io
        
