name: Understanding matrix strategy
on:
  workflow_dispatch:

jobs:
  understanding_matrix:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16, 18, 20]

    steps:
      - name: Checkout repo code
        uses: actions/checkout@v4.2.2

      - name: Installing node version
        uses: actions/setup-node@v3.9.1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Installing packages
        run: |
          if [ -f package.json ]; then npm install; fi
        
