name: Configuring aws and list s3 buckets

on:
  workflow_dispatch:

jobs:
  testing-secrets:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4.2.2

      - name: Configure aws
        uses: aws-actions/configure-aws-credentials@v4.1.0
        with:
          aws-region: ${{ secret.AWS_REGION }}
          aws-access-key-id: ${{ secret.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secret.AWS_SECRET_ACCESS_KEY }}

      - name: List the s3 bucket
        run: aws s3 ls
