name: Testing github secret
on:
  workflow_dispatch:

jobs:
  understanding_secret:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code repo
        uses: actions/checkout@v4.2.2

      - name: Print secret key the wrong way
        run: echo "$SECRET_KEY"

      - name: Print secret key the correct way
        run: echo "${{ secrets.SECRET_KEY }}"

      - name: Print secret key the safer way
        env:
          SECRET_KEY: ${{ secrets.SECRET_KEY }}
        run: echo "$SECRET_KEY"
        
