name: Understanding tags with ECR

on:
  push:
    tags: "v*"

jobs:
  understanding_tags:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v4.2.2

      - name: Configure aws
        uses: aws-actions/configure-aws-credentials@v4.1.0
        with:
          aws-region: ${{ secrets.AWS_REGION }}
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Login to ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: To build and tag Docker image
        run: |
          TAG=${GITHUB_REF#refs/tags/}
          docker build -t understanding-github-tag-actions .
          docker tag understanding-github-tag-actions:$TAG 935398764279.dkr.ecr.ap-south-1.amazonaws.com/understanding-github-tag-actions:$TAG

      - name: Push the docker image
        run: |
          TAG=${GITHUB_REF#refs/tags/}
          docker push 935398764279.dkr.ecr.ap-south-1.amazonaws.com/understanding-github-tag-actions:$TAG
          
        

